### PR TITLE
Created Linked List

### PR DESCRIPTION
**Pull request by kodevyas**
Fixes #[#43]

Language: [c]

### CODE REVIEW

**Comment by piyush6348** [comment]
thanks @kodevyas for contribution.
How will you add new values in Linked List at runtime?
Please make a function that takes a data and adds it to end of linked list 

Happy HacktoberFest
Keep contributing

**Comment by kodevyas** [comment]
Fixes #[#43]

Language: [c]

**Comment by piyush6348** [comment]
make all the functions in one rather than making separate files for each one of them

Happy HacktoberFest
Keep contributing

**Comment by nimit95** [comment]
Change and make a new PR

**Pull request closed without merging**
